package net.sf.l2j.cms.models

import net.sf.l2j.Config

data class SevenSignsConfig(
    var ALT_GAME_CASTLE_DAWN: Boolean = Config.ALT_GAME_CASTLE_DAWN,
    var ALT_GAME_CASTLE_DUSK: Boolean = Config.ALT_GAME_CASTLE_DUSK,
    var ALT_FESTIVAL_MIN_PLAYER: Int = Config.ALT_FESTIVAL_MIN_PLAYER,
    var ALT_MAXIMUM_PLAYER_CONTRIB: Int = Config.ALT_MAXIMUM_PLAYER_CONTRIB,
    var ALT_FESTIVAL_MANAGER_START: Long = Config.ALT_FESTIVAL_MANAGER_START,
    var ALT_FESTIVAL_LENGTH: Long = Config.ALT_FESTIVAL_LENGTH,
    var ALT_FESTIVAL_CYCLE_LENGTH: Long = Config.ALT_FESTIVAL_CYCLE_LENGTH,
    var ALT_FESTIVAL_FIRST_SPAWN: Long = Config.ALT_FESTIVAL_FIRST_SPAWN,
    var ALT_FESTIVAL_FIRST_SWARM: Long = Config.ALT_FESTIVAL_FIRST_SWARM,
    var ALT_FESTIVAL_SECOND_SPAWN: Long = Config.ALT_FESTIVAL_SECOND_SPAWN,
    var ALT_FESTIVAL_SECOND_SWARM: Long = Config.ALT_FESTIVAL_SECOND_SWARM,
    var ALT_FESTIVAL_CHEST_SPAWN: Long = Config.ALT_FESTIVAL_CHEST_SPAWN
) {
    companion object {
        val fieldMap = mapOf(
            "ALT_GAME_CASTLE_DAWN" to Config::ALT_GAME_CASTLE_DAWN,
            "ALT_GAME_CASTLE_DUSK" to Config::ALT_GAME_CASTLE_DUSK,
            "ALT_FESTIVAL_MIN_PLAYER" to Config::ALT_FESTIVAL_MIN_PLAYER,
            "ALT_MAXIMUM_PLAYER_CONTRIB" to Config::ALT_MAXIMUM_PLAYER_CONTRIB,
            "ALT_FESTIVAL_MANAGER_START" to Config::ALT_FESTIVAL_MANAGER_START,
            "ALT_FESTIVAL_LENGTH" to Config::ALT_FESTIVAL_LENGTH,
            "ALT_FESTIVAL_CYCLE_LENGTH" to Config::ALT_FESTIVAL_CYCLE_LENGTH,
            "ALT_FESTIVAL_FIRST_SPAWN" to Config::ALT_FESTIVAL_FIRST_SPAWN,
            "ALT_FESTIVAL_FIRST_SWARM" to Config::ALT_FESTIVAL_FIRST_SWARM,
            "ALT_FESTIVAL_SECOND_SPAWN" to Config::ALT_FESTIVAL_SECOND_SPAWN,
            "ALT_FESTIVAL_SECOND_SWARM" to Config::ALT_FESTIVAL_SECOND_SWARM,
            "ALT_FESTIVAL_CHEST_SPAWN" to Config::ALT_FESTIVAL_CHEST_SPAWN
        )
    }
}
